
This is Set 5: Column Aggregations (Exercises 41-50) of Polars Exercises: 💯 polars exercises You can find all the exercises and solutions on [GitHub](https://github.com/JustinKurland/polars_practice)

**Prerequisites**

*   The `polars` package should be upgraded to the latest version (v0.15.1+).
*   The sample dataset [wine](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_wine.html) from `sklearn` will be used for the exercises.

In [4]:
!pip install polars
!pip install scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: polars in /usr/local/lib/python3.8/dist-packages (0.15.7)
Requirement already satisfied: typing_extensions>=4.0.0 in /usr/local/lib/python3.8/dist-packages (from polars) (4.4.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.8/dist-packages (1.0.2)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.8/dist-packages (from scikit-learn) (1.21.6)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn) (1.7.3)

In [5]:
import polars as pl
from sklearn.datasets import load_wine

data = pl.DataFrame(load_wine(as_frame=True).frame)
data

shape: (178, 14)
┌─────────┬────────────┬──────┬──────────────────┬─────┬──────┬─────────────────┬─────────┬────────┐
│ alcohol ┆ malic_acid ┆ ash  ┆ alcalinity_of_as ┆ ... ┆ hue  ┆ od280/od315_of_ ┆ proline ┆ target │
│ ---     ┆ ---        ┆ ---  ┆ h                ┆     ┆ ---  ┆ diluted_wines   ┆ ---     ┆ ---    │
│ f64     ┆ f64        ┆ f64  ┆ ---              ┆     ┆ f64  ┆ ---             ┆ f64     ┆ i64    │
│         ┆            ┆      ┆ f64              ┆     ┆      ┆ f64             ┆         ┆        │
╞═════════╪════════════╪══════╪══════════════════╪═════╪══════╪═════════════════╪═════════╪════════╡
│ 14.23   ┆ 1.71       ┆ 2.43 ┆ 15.6             ┆ ... ┆ 1.04 ┆ 3.92            ┆ 1065.0  ┆ 0      │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 13.2    ┆ 1.78       ┆ 2.14 ┆ 11.2             ┆ ... ┆ 1.05 ┆ 3.4             ┆ 1050.0  ┆ 0      │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 13.16   ┆ 2.36       ┆ 2.67 ┆ 18.6             ┆ ... ┆ 1.03 ┆ 3.17            ┆ 1185.0  ┆ 0      │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 14.37   ┆ 1.95       ┆ 2.5  ┆ 16.8             ┆ ... ┆ 0.86 ┆ 3.45            ┆ 1480.0  ┆ 0      │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ ...     ┆ ...        ┆ ...  ┆ ...              ┆ ... ┆ ...  ┆ ...             ┆ ...     ┆ ...    │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 13.4    ┆ 3.91       ┆ 2.48 ┆ 23.0             ┆ ... ┆ 0.7  ┆ 1.56            ┆ 750.0   ┆ 2      │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 13.27   ┆ 4.28       ┆ 2.26 ┆ 20.0             ┆ ... ┆ 0.59 ┆ 1.56            ┆ 835.0   ┆ 2      │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 13.17   ┆ 2.59       ┆ 2.37 ┆ 20.0             ┆ ... ┆ 0.6  ┆ 1.62            ┆ 840.0   ┆ 2      │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 14.13   ┆ 4.1        ┆ 2.74 ┆ 24.5             ┆ ... ┆ 0.61 ┆ 1.6             ┆ 560.0   ┆ 2      │
└─────────┴────────────┴──────┴──────────────────┴─────┴──────┴─────────────────┴─────────┴────────┘

**Exercise 41: Calculate the sum of column `ash` in `data`**

In [6]:
data['ash'].sum()

421.23999999999995

**Exercise 42: Calculate the average value of each column in `data`**

In [7]:
data.mean()

shape: (1, 14)
┌───────────┬──────────┬──────────┬────────────┬─────┬──────────┬────────────┬──────────┬──────────┐
│ alcohol   ┆ malic_ac ┆ ash      ┆ alcalinity ┆ ... ┆ hue      ┆ od280/od31 ┆ proline  ┆ target   │
│ ---       ┆ id       ┆ ---      ┆ _of_ash    ┆     ┆ ---      ┆ 5_of_dilut ┆ ---      ┆ ---      │
│ f64       ┆ ---      ┆ f64      ┆ ---        ┆     ┆ f64      ┆ ed_wines   ┆ f64      ┆ f64      │
│           ┆ f64      ┆          ┆ f64        ┆     ┆          ┆ ---        ┆          ┆          │
│           ┆          ┆          ┆            ┆     ┆          ┆ f64        ┆          ┆          │
╞═══════════╪══════════╪══════════╪════════════╪═════╪══════════╪════════════╪══════════╪══════════╡
│ 13.000618 ┆ 2.336348 ┆ 2.366517 ┆ 19.494944  ┆ ... ┆ 0.957449 ┆ 2.611685   ┆ 746.8932 ┆ 0.938202 │
│           ┆          ┆          ┆            ┆     ┆          ┆            ┆ 58       ┆          │
└───────────┴──────────┴──────────┴────────────┴─────┴──────────┴────────────┴──────────┴──────────┘

**Exercise 43: Calculate the minimum value and maximum value of each column in `data` where `target` is 1**

In [8]:
data.filter(pl.col('target') == 1).min()

shape: (1, 14)
┌─────────┬────────────┬──────┬──────────────────┬─────┬──────┬─────────────────┬─────────┬────────┐
│ alcohol ┆ malic_acid ┆ ash  ┆ alcalinity_of_as ┆ ... ┆ hue  ┆ od280/od315_of_ ┆ proline ┆ target │
│ ---     ┆ ---        ┆ ---  ┆ h                ┆     ┆ ---  ┆ diluted_wines   ┆ ---     ┆ ---    │
│ f64     ┆ f64        ┆ f64  ┆ ---              ┆     ┆ f64  ┆ ---             ┆ f64     ┆ i64    │
│         ┆            ┆      ┆ f64              ┆     ┆      ┆ f64             ┆         ┆        │
╞═════════╪════════════╪══════╪══════════════════╪═════╪══════╪═════════════════╪═════════╪════════╡
│ 11.03   ┆ 0.74       ┆ 1.36 ┆ 10.6             ┆ ... ┆ 0.69 ┆ 1.59            ┆ 278.0   ┆ 1      │
└─────────┴────────────┴──────┴──────────────────┴─────┴──────┴─────────────────┴─────────┴────────┘

In [9]:
data.filter(pl.col('target') == 1).max()

shape: (1, 14)
┌─────────┬────────────┬──────┬──────────────────┬─────┬──────┬─────────────────┬─────────┬────────┐
│ alcohol ┆ malic_acid ┆ ash  ┆ alcalinity_of_as ┆ ... ┆ hue  ┆ od280/od315_of_ ┆ proline ┆ target │
│ ---     ┆ ---        ┆ ---  ┆ h                ┆     ┆ ---  ┆ diluted_wines   ┆ ---     ┆ ---    │
│ f64     ┆ f64        ┆ f64  ┆ ---              ┆     ┆ f64  ┆ ---             ┆ f64     ┆ i64    │
│         ┆            ┆      ┆ f64              ┆     ┆      ┆ f64             ┆         ┆        │
╞═════════╪════════════╪══════╪══════════════════╪═════╪══════╪═════════════════╪═════════╪════════╡
│ 13.86   ┆ 5.8        ┆ 3.23 ┆ 30.0             ┆ ... ┆ 1.71 ┆ 3.69            ┆ 985.0   ┆ 1      │
└─────────┴────────────┴──────┴──────────────────┴─────┴──────┴─────────────────┴─────────┴────────┘

**Exercise 44: Calculate the median value of columns `flavanoids`, `hue` and `magnesium` in `data`**

In [10]:
data[['flavanoids', 'hue', 'magnesium']].median()

shape: (1, 3)
┌────────────┬───────┬───────────┐
│ flavanoids ┆ hue   ┆ magnesium │
│ ---        ┆ ---   ┆ ---       │
│ f64        ┆ f64   ┆ f64       │
╞════════════╪═══════╪═══════════╡
│ 2.135      ┆ 0.965 ┆ 98.0      │
└────────────┴───────┴───────────┘

**Exercise 45: Calculate the mode of column `magnesium` in `data`**

In [11]:
data.with_column(pl.col('magnesium').cast(pl.Int64, strict=False)).select([pl.col("magnesium").mode()])

shape: (1, 1)
┌───────────┐
│ magnesium │
│ ---       │
│ i64       │
╞═══════════╡
│ 88        │
└───────────┘

**Exercise 46: Calculate the standard deviation, skewness and excess kurtosis of each column in `data`**

In [12]:
data.std()

shape: (1, 14)
┌──────────┬──────────┬──────────┬────────────┬─────┬──────────┬────────────┬───────────┬──────────┐
│ alcohol  ┆ malic_ac ┆ ash      ┆ alcalinity ┆ ... ┆ hue      ┆ od280/od31 ┆ proline   ┆ target   │
│ ---      ┆ id       ┆ ---      ┆ _of_ash    ┆     ┆ ---      ┆ 5_of_dilut ┆ ---       ┆ ---      │
│ f64      ┆ ---      ┆ f64      ┆ ---        ┆     ┆ f64      ┆ ed_wines   ┆ f64       ┆ f64      │
│          ┆ f64      ┆          ┆ f64        ┆     ┆          ┆ ---        ┆           ┆          │
│          ┆          ┆          ┆            ┆     ┆          ┆ f64        ┆           ┆          │
╞══════════╪══════════╪══════════╪════════════╪═════╪══════════╪════════════╪═══════════╪══════════╡
│ 0.811827 ┆ 1.117146 ┆ 0.274344 ┆ 3.339564   ┆ ... ┆ 0.228572 ┆ 0.70999    ┆ 314.90747 ┆ 0.775035 │
│          ┆          ┆          ┆            ┆     ┆          ┆            ┆ 4         ┆          │
└──────────┴──────────┴──────────┴────────────┴─────┴──────────┴────────────┴───────────┴──────────┘

In [13]:
data.select(pl.col('*').skew())

shape: (1, 14)
┌───────────┬──────────┬───────────┬────────────┬─────┬──────────┬────────────┬──────────┬──────────┐
│ alcohol   ┆ malic_ac ┆ ash       ┆ alcalinity ┆ ... ┆ hue      ┆ od280/od31 ┆ proline  ┆ target   │
│ ---       ┆ id       ┆ ---       ┆ _of_ash    ┆     ┆ ---      ┆ 5_of_dilut ┆ ---      ┆ ---      │
│ f64       ┆ ---      ┆ f64       ┆ ---        ┆     ┆ f64      ┆ ed_wines   ┆ f64      ┆ f64      │
│           ┆ f64      ┆           ┆ f64        ┆     ┆          ┆ ---        ┆          ┆          │
│           ┆          ┆           ┆            ┆     ┆          ┆ f64        ┆          ┆          │
╞═══════════╪══════════╪═══════════╪════════════╪═════╪══════════╪════════════╪══════════╪══════════╡
│ -0.051047 ┆ 1.030869 ┆ -0.175207 ┆ 0.211247   ┆ ... ┆ 0.020913 ┆ -0.30469   ┆ 0.761336 ┆ 0.106524 │
└───────────┴──────────┴───────────┴────────────┴─────┴──────────┴────────────┴──────────┴──────────┘

In [14]:
data.select(pl.col('*').kurtosis())

shape: (1, 14)
┌──────────┬──────────┬──────────┬────────────┬─────┬───────────┬────────────┬─────────┬──────────┐
│ alcohol  ┆ malic_ac ┆ ash      ┆ alcalinity ┆ ... ┆ hue       ┆ od280/od31 ┆ proline ┆ target   │
│ ---      ┆ id       ┆ ---      ┆ _of_ash    ┆     ┆ ---       ┆ 5_of_dilut ┆ ---     ┆ ---      │
│ f64      ┆ ---      ┆ f64      ┆ ---        ┆     ┆ f64       ┆ ed_wines   ┆ f64     ┆ f64      │
│          ┆ f64      ┆          ┆ f64        ┆     ┆           ┆ ---        ┆         ┆          │
│          ┆          ┆          ┆            ┆     ┆           ┆ f64        ┆         ┆          │
╞══════════╪══════════╪══════════╪════════════╪═════╪═══════════╪════════════╪═════════╪══════════╡
│ -0.86226 ┆ 0.257348 ┆ 1.078576 ┆ 0.440823   ┆ ... ┆ -0.368025 ┆ -1.089675  ┆ -0.275  ┆ -1.31944 │
└──────────┴──────────┴──────────┴────────────┴─────┴───────────┴────────────┴─────────┴──────────┘

**Exercise 47: Calculate the number of unique values in each column of data**

In [15]:
#data.select(pl.col('*').unique_counts())
data.select(pl.n_unique("*"))

shape: (1, 14)
┌─────────┬────────────┬─────┬───────────────────┬─────┬─────┬──────────────────┬─────────┬────────┐
│ alcohol ┆ malic_acid ┆ ash ┆ alcalinity_of_ash ┆ ... ┆ hue ┆ od280/od315_of_d ┆ proline ┆ target │
│ ---     ┆ ---        ┆ --- ┆ ---               ┆     ┆ --- ┆ iluted_wines     ┆ ---     ┆ ---    │
│ u32     ┆ u32        ┆ u32 ┆ u32               ┆     ┆ u32 ┆ ---              ┆ u32     ┆ u32    │
│         ┆            ┆     ┆                   ┆     ┆     ┆ u32              ┆         ┆        │
╞═════════╪════════════╪═════╪═══════════════════╪═════╪═════╪══════════════════╪═════════╪════════╡
│ 126     ┆ 133        ┆ 79  ┆ 63                ┆ ... ┆ 78  ┆ 122              ┆ 121     ┆ 3      │
└─────────┴────────────┴─────┴───────────────────┴─────┴─────┴──────────────────┴─────────┴────────┘

**Exercise 48: Calculate the covariance between columns `alcohol` and `color_intensity` in `data`**

In [16]:
data.select(pl.cov("alcohol", "color_intensity"))

shape: (1, 1)
┌──────────┐
│ alcohol  │
│ ---      │
│ f64      │
╞══════════╡
│ 1.028283 │
└──────────┘

**Exercise 49: Calculate Pearson correlation and Spearman Rank correlation between columns `hue` and `color_intensity` in `data`**

In [17]:
data.select(pl.pearson_corr("hue", "color_intensity"))

shape: (1, 1)
┌───────────┐
│ hue       │
│ ---       │
│ f64       │
╞═══════════╡
│ -0.521813 │
└───────────┘

In [18]:
data.select(pl.spearman_rank_corr("hue", "color_intensity"))

shape: (1, 1)
┌───────────┐
│ hue       │
│ ---       │
│ f64       │
╞═══════════╡
│ -0.419825 │
└───────────┘

**Exercise 50: Calculate the correlation matrix between all pairs of columns in `data` and assign it to `corr_matrix`**

In [23]:
corr_matrix = data.pearson_corr()
col_names = corr_matrix.columns
corr_matrix = corr_matrix.with_column(pl.Series(name="Columns", values=col_names))
corr_matrix = corr_matrix[['Columns'] + [ col for col in corr_matrix.columns if col != 'Columns' ]]
corr_matrix

shape: (14, 15)
┌───────────┬───────────┬──────────┬───────────┬─────┬──────────┬────────────┬──────────┬──────────┐
│ Columns   ┆ alcohol   ┆ malic_ac ┆ ash       ┆ ... ┆ hue      ┆ od280/od31 ┆ proline  ┆ target   │
│ ---       ┆ ---       ┆ id       ┆ ---       ┆     ┆ ---      ┆ 5_of_dilut ┆ ---      ┆ ---      │
│ str       ┆ f64       ┆ ---      ┆ f64       ┆     ┆ f64      ┆ ed_wines   ┆ f64      ┆ f64      │
│           ┆           ┆ f64      ┆           ┆     ┆          ┆ ---        ┆          ┆          │
│           ┆           ┆          ┆           ┆     ┆          ┆ f64        ┆          ┆          │
╞═══════════╪═══════════╪══════════╪═══════════╪═════╪══════════╪════════════╪══════════╪══════════╡
│ alcohol   ┆ 1.0       ┆ 0.094397 ┆ 0.211545  ┆ ... ┆ -0.07174 ┆ 0.072343   ┆ 0.64372  ┆ -0.32822 │
│           ┆           ┆          ┆           ┆     ┆ 7        ┆            ┆          ┆ 2        │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ malic_aci ┆ 0.094397  ┆ 1.0      ┆ 0.164045  ┆ ... ┆ -0.56129 ┆ -0.36871   ┆ -0.19201 ┆ 0.437776 │
│ d         ┆           ┆          ┆           ┆     ┆ 6        ┆            ┆ 1        ┆          │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ ash       ┆ 0.211545  ┆ 0.164045 ┆ 1.0       ┆ ... ┆ -0.07466 ┆ 0.003911   ┆ 0.223626 ┆ -0.04964 │
│           ┆           ┆          ┆           ┆     ┆ 7        ┆            ┆          ┆ 3        │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ alcalinit ┆ -0.310235 ┆ 0.2885   ┆ 0.443367  ┆ ... ┆ -0.27395 ┆ -0.276769  ┆ -0.44059 ┆ 0.517859 │
│ y_of_ash  ┆           ┆          ┆           ┆     ┆ 5        ┆            ┆ 7        ┆          │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ ...       ┆ ...       ┆ ...      ┆ ...       ┆ ... ┆ ...      ┆ ...        ┆ ...      ┆ ...      │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ hue       ┆ -0.071747 ┆ -0.56129 ┆ -0.074667 ┆ ... ┆ 1.0      ┆ 0.565468   ┆ 0.236183 ┆ -0.61736 │
│           ┆           ┆ 6        ┆           ┆     ┆          ┆            ┆          ┆ 9        │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ od280/od3 ┆ 0.072343  ┆ -0.36871 ┆ 0.003911  ┆ ... ┆ 0.565468 ┆ 1.0        ┆ 0.312761 ┆ -0.78823 │
│ 15_of_dil ┆           ┆          ┆           ┆     ┆          ┆            ┆          ┆          │
│ uted_wine ┆           ┆          ┆           ┆     ┆          ┆            ┆          ┆          │
│ s         ┆           ┆          ┆           ┆     ┆          ┆            ┆          ┆          │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ proline   ┆ 0.64372   ┆ -0.19201 ┆ 0.223626  ┆ ... ┆ 0.236183 ┆ 0.312761   ┆ 1.0      ┆ -0.63371 │
│           ┆           ┆ 1        ┆           ┆     ┆          ┆            ┆          ┆ 7        │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┤
│ target    ┆ -0.328222 ┆ 0.437776 ┆ -0.049643 ┆ ... ┆ -0.61736 ┆ -0.78823   ┆ -0.63371 ┆ 1.0      │
│           ┆           ┆          ┆           ┆     ┆ 9        ┆            ┆ 7        ┆          │
└───────────┴───────────┴──────────┴───────────┴─────┴──────────┴────────────┴──────────┴──────────┘